name: EmailAction

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 23f2003711@ds.study.iitm.ac.in
        run: echo "Hello, world!"
